# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('Billing_ID', models.AutoField(help_text='Autogenerated Primary Key', primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now=True, help_text='When operation have been made (Day only)')),
                ('OperationIsTraining', models.BooleanField(blank=True, help_text='The operation logged is a training', null=True)),
                ('CountOfLinesTraining', models.IntegerField(blank=True, null=True)),
                ('CountOfTrainingEpoch', models.IntegerField(blank=True, null=True)),
                ('TrainingCostMachineOwnerUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Price to be billed to Operation_User_ID', max_digits=11, null=True)),
                ('OperationIsSolving', models.BooleanField(blank=True, help_text='The operation logged is a solving by the owner', null=True)),
                ('CountOfLinesSolved', models.IntegerField(blank=True, help_text='How many lines solved', null=True)),
                ('SolvingCostMachineOwnerUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid by Operation_User_ID', max_digits=11, null=True)),
                ('OperationIsSolvingAPI', models.BooleanField(blank=True, help_text='The operation logged is a solving by user not owner, so the owner is paid by user', null=True)),
                ('SolvingCostReceivedByMachineOwnerUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Amount received by Machine_User_ID', max_digits=11, null=True)),
                ('SolvingCostSoldExternalUserUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid by Operation_User_ID ', max_digits=11, null=True)),
                ('OperationIsMachineCopy', models.BooleanField(blank=True, help_text='The operation was a Machine duplication', null=True)),
                ('MachineCopyCostReceivedMachineOwnerUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to receive from operation sold to External User _ to received by Machine_User_ID', max_digits=11, null=True)),
                ('MachineCopyCostSoldExternalUserUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Price paid by Operation_User_ID', max_digits=11, null=True)),
                ('OperationIsMachineCopyUpdate', models.BooleanField(blank=True, help_text='The operation was a Machine duplicate Update', null=True)),
                ('MachineCopyUpdateCostReceivedMachineOwnerUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to receive from operation sold to External User _ to received by Machine_User_ID', max_digits=11, null=True)),
                ('MachineCopyUpdateCostSoldExternalUserUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Price paid by Operation_User_ID', max_digits=11, null=True)),
                ('OperationIsMachineExport', models.BooleanField(blank=True, help_text='The operation was a Machine export to Python', null=True)),
                ('MachineExportCostReceivedMachineOwnerUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to receive from operation sold to External User _ to received by Machine_User_ID', max_digits=11, null=True)),
                ('MachineExportCostSoldExternalUserUSD', models.DecimalField(blank=True, decimal_places=2, help_text='Price paid by Operation_User_ID', max_digits=11, null=True)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
                'db_table': 'Billing',
            },
        ),
    ]
