# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Machine_ID',
            field=models.ForeignKey(blank=True, help_text='Machine performing operation', null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine'),
        ),
    ]
