# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_billing_machine_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Machine_Owner_User_ID',
            field=models.ForeignKey(blank=True, help_text='Machine=>Owner_User_ID  at the moment when the billing was created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Machine_Owner_User_ID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billing',
            name='Operation_User_ID',
            field=models.ForeignKey(blank=True, help_text='User performing the operation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operation_User_ID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['Billing_ID'], name='Billing_Billing_08e2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['Machine_ID'], name='Billing_Machine_3f932c_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['Machine_Owner_User_ID'], name='Billing_Machine_18c2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['Operation_User_ID'], name='Billing_Operati_850795_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['Date'], name='Billing_Date_b4aa6b_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['OperationIsTraining'], name='Billing_Operati_638e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['OperationIsSolving'], name='Billing_Operati_544340_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['OperationIsMachineCopy'], name='Billing_Operati_2cc898_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['OperationIsMachineCopyUpdate'], name='Billing_Operati_6a1b10_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['OperationIsMachineExport'], name='Billing_Operati_2c7e46_idx'),
        ),
    ]
