# Generated by Django 2.2.4 on 2019-12-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(help_text='The Team are connected to AccessRight, users can have several companies, and companies can have several users, to make this we have a TABLE AccessRight ', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'Team',
            },
        ),
    ]
