# Generated by Django 2.2.4 on 2019-12-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_ID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=200, verbose_name='Name')),
                ('AdminUser_ID', models.ManyToManyField(to='user.User')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'Team',
            },
        ),
    ]
