# Generated by Django 2.2.4 on 2019-12-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('Graph_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTimeCreation', models.DateTimeField(auto_now=True)),
                ('GraphType', models.CharField(default='1', max_length=255)),
                ('ColorScaleSet', models.CharField(default='1', max_length=255)),
                ('X', models.CharField(default='', max_length=255)),
                ('Y', models.CharField(default='', max_length=255)),
                ('Z', models.CharField(default='', max_length=255)),
                ('Color', models.CharField(default='', max_length=255)),
                ('Animation_Frame', models.CharField(default='', max_length=255, null=True)),
                ('Machine_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Machine')),
            ],
            options={
                'verbose_name': 'Graph',
                'verbose_name_plural': 'Graphs',
                'db_table': 'Graph',
            },
        ),
    ]
