# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='Machine_ID',
            field=models.ForeignKey(help_text='The graph belong to this machine/Machine', on_delete=django.db.models.deletion.CASCADE, to='machine.Machine'),
        ),
    ]
