# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('Work_ID', models.AutoField(help_text='Auto incremential ID', primary_key=True, serialize=False)),
                ('CreationDateTime', models.DateTimeField(auto_now_add=True, help_text='When This work have been created')),
                ('IsWorkTraining', models.BooleanField(blank=True, help_text='Always one value is TRUE simultanousely', null=True)),
                ('IsWorkSolving', models.BooleanField(blank=True, help_text='Always one value is TRUE simultanousely', null=True)),
                ('IsWorkStatusWaitForServerStart', models.BooleanField(blank=True, help_text='Always one value is TRUE simultanousely', null=True)),
                ('IsWorkStatusServerProcessing', models.BooleanField(blank=True, help_text='Always one value is TRUE simultanousely', null=True)),
                ('IsWorkStatusServerFinished', models.BooleanField(blank=True, help_text='Always one value is TRUE simultanousely', null=True)),
                ('DataLineToProcess_FirstLineID', models.IntegerField(blank=True, help_text='Because replication is progressive, to check if this line is available before to start processing the work', null=True)),
                ('DataLineToProcess_LastLineID', models.IntegerField(blank=True, help_text='Because replication is progressive, to check if this line is available before to start processing the work', null=True)),
                ('WorkStartedAtDateTime', models.DateTimeField(auto_now=True)),
                ('WorkStartedByServerName', models.CharField(default='', max_length=45)),
                ('WorkStartedCountOfLineToProcess', models.IntegerField(blank=True, null=True)),
                ('WorkDurationEstimationSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('WorkFinishedAtDateTime', models.DateTimeField(blank=True, null=True)),
                ('WorkFinishedByServerName', models.CharField(default='', max_length=45)),
                ('WorkFinishedCountOfLineToProcess', models.IntegerField(blank=True, null=True)),
                ('WorkFinishedDurationSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Learning_DelayElapsedSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Solving_DelayElapsedSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('TextError', jsonfield.fields.JSONField(default=[])),
                ('TextWarning', jsonfield.fields.JSONField(default=[])),
                ('Machine_ID', models.ForeignKey(blank=True, help_text='To Process this Machine', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Works', to='machine.Machine')),
                ('ServerName', models.ForeignKey(blank=True, help_text='Name of server to do the work', null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Server', to_field='ServerName')),
            ],
            options={
                'db_table': 'Work',
            },
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['Work_ID'], name='Work_Work_ID_0ae54c_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['CreationDateTime'], name='Work_Creatio_45ca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['Machine_ID'], name='Work_Machine_b12d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['ServerName'], name='Work_ServerN_293110_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['IsWorkStatusWaitForServerStart'], name='Work_IsWorkS_6d4abc_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['IsWorkStatusServerProcessing'], name='Work_IsWorkS_63bc04_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['IsWorkStatusServerFinished'], name='Work_IsWorkS_54db5a_idx'),
        ),
    ]
