# Generated by Django 2.2.4 on 2019-12-03 16:16

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '__first__'),
        ('machine', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('Work_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CreationDateTime', models.DateTimeField(auto_now=True)),
                ('IsWorkTraining', models.BooleanField(blank=True, null=True)),
                ('IsWorkSolving', models.BooleanField(blank=True, null=True)),
                ('IsWorkStatusWaitForServerStart', models.BooleanField(blank=True, null=True)),
                ('IsWorkStatusServerProcessing', models.BooleanField(blank=True, null=True)),
                ('IsWorkStatusServerFinished', models.BooleanField(blank=True, null=True)),
                ('DataLineToProcess_FirstLineID', models.IntegerField(blank=True, null=True)),
                ('DataLineToProcess_LastLineID', models.IntegerField(blank=True, null=True)),
                ('WorkStartedAtDateTime', models.DateTimeField(auto_now=True)),
                ('WorkStartedByServerName', models.CharField(default='', max_length=45)),
                ('WorkStartedCountOfLineToProcess', models.IntegerField(blank=True, null=True)),
                ('WorkDurationEstimationSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('WorkFinishedAtDateTime', models.DateTimeField(blank=True, null=True)),
                ('WorkFinishedByServerName', models.CharField(default='', max_length=45)),
                ('WorkFinishedCountOfLineToProcess', models.IntegerField(blank=True, null=True)),
                ('WorkFinishedDurationSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Learning_DelayElapsedSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('Solving_DelayElapsedSeconds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('TextError', jsonfield.fields.JSONField(default=[])),
                ('TextWarning', jsonfield.fields.JSONField(default=[])),
                ('Machine_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine')),
                ('ServerName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Server')),
            ],
            options={
                'db_table': 'Work',
            },
        ),
    ]
