# Generated by Django 2.2.4 on 2019-11-14 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_new_machine', models.BooleanField(verbose_name='A New Machine')),
                ('request', models.TextField(help_text='Please describe your request.', verbose_name='Request')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine', verbose_name='An Existing Machine')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Consulting Request',
                'verbose_name_plural': 'Consulting Requests',
            },
        ),
        migrations.CreateModel(
            name='ConsultingRequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='consultingrequest/%Y-%m-%d/%H-%M', verbose_name='file')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('consulting_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulting.ConsultingRequest', verbose_name='consulting request')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulting Request File',
                'verbose_name_plural': 'Consulting Request Files',
            },
        ),
    ]
