# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantApplication',
            fields=[
                ('ConsultingApplication_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BidUSD', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ConsultantApplication',
            },
        ),
        migrations.CreateModel(
            name='ConsultingRequest',
            fields=[
                ('ConsultingRequest_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTimeCreation', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(blank=True)),
                ('Files_1', models.BinaryField(blank=True, null=True)),
                ('Files_2', models.BinaryField(blank=True, null=True)),
                ('Files_3', models.BinaryField(blank=True, null=True)),
                ('IsStatusRequest', models.BooleanField(blank=True, null=True)),
                ('IsStatusWaitingConsultantApproval', models.BooleanField(blank=True, null=True)),
                ('WaitingConsultantApprovalDateTime', models.DateTimeField(blank=True, null=True)),
                ('IsStatusContract', models.BooleanField(blank=True, null=True)),
                ('ContractStartDateTime', models.DateTimeField(blank=True, null=True)),
                ('IsStatusContractFinished', models.BooleanField(blank=True, null=True)),
                ('IsStatusContractFailed', models.BooleanField(blank=True, null=True)),
                ('IsStatusContractCancel', models.BooleanField(blank=True, null=True)),
                ('ContractEndDateTime', models.DateTimeField(blank=True, null=True)),
                ('AmountUSD', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'ConsultingRequest',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Message_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTimeCreation', models.DateTimeField(auto_now_add=True, help_text='date of message (DateTimeChat)')),
                ('Message', models.TextField(blank=True, help_text='Text of the message')),
                ('File', models.BinaryField(blank=True, help_text='One file', null=True)),
                ('Recipient_ConsultingRequest_ID', models.ForeignKey(blank=True, help_text='Optional (only one destination simultanousely) _ Message sent to this consultingRequest (only if the message is part of consultingRequest Discussion)', null=True, on_delete=django.db.models.deletion.CASCADE, to='consulting.ConsultingRequest')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'Message',
            },
        ),
    ]
