# Generated by Django 2.2.4 on 2019-12-03 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingRequest',
            fields=[
                ('ConsultingRequest_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTimeCreation', models.DateTimeField(auto_now=True)),
                ('Description', models.TextField(blank=True)),
                ('Files_1', models.BinaryField(blank=True, null=True)),
                ('Files_2', models.BinaryField(blank=True, null=True)),
                ('Files_3', models.BinaryField(blank=True, null=True)),
                ('IsStatusRequest', models.BooleanField(blank=True, null=True)),
                ('IsStatusWaitingConsultantApproval', models.BooleanField(blank=True, null=True)),
                ('WaitingConsultantApprovalDateTime', models.DateTimeField(blank=True, null=True)),
                ('IsStatusContract', models.BooleanField(blank=True, null=True)),
                ('ContractStartDateTime', models.DateTimeField(blank=True, null=True)),
                ('IsStatusContractFinished', models.BooleanField(blank=True, null=True)),
                ('IsStatusContractFailed', models.BooleanField(blank=True, null=True)),
                ('IsStatusContractCancel', models.BooleanField(blank=True, null=True)),
                ('ContractEndDateTime', models.DateTimeField(blank=True, null=True)),
                ('AmountUSD', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('Consultant_User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consultant_User_ID', to=settings.AUTH_USER_MODEL)),
                ('Machine_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine')),
                ('Team_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ConsultingRequest',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Message_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTimeCreation', models.DateTimeField(auto_now=True)),
                ('Message', models.TextField(blank=True)),
                ('File', models.BinaryField(blank=True, null=True)),
                ('Recipient_ConsultingRequest_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulting.ConsultingRequest')),
                ('Recipient_Machine_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine')),
                ('Recipient_User_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recipient_User_ID', to=settings.AUTH_USER_MODEL)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='ConsultantApplication',
            fields=[
                ('ConsultingApplication_ID', models.AutoField(primary_key=True, serialize=False)),
                ('BidUSD', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('ConsultingRequest_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulting.ConsultingRequest')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ConsultantApplication',
            },
        ),
    ]
