# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Recipient_Machine_ID',
            field=models.ForeignKey(blank=True, help_text='Optional (only one destination simultanousely) _ Message sent to this Machine Discussion (only if ity is sent to a machine discussion) ', null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Machine'),
        ),
    ]
