# Generated by Django 2.2.4 on 2019-12-04 12:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='AnalysisSource_ColumnType',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='machine',
            name='AnalysisSource_ColumnsNameInput',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='machine',
            name='AnalysisSource_ColumnsNameOutput',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='machine',
            name='DateTimeCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
