# Generated by Django 2.2.4 on 2019-12-05 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinemessage',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Machine', verbose_name='machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='MultipleMachine_Aggregator_Machine_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MachineAggregator', to='machine.Machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='MultipleMachine_Elements_Machine_ID',
            field=models.ManyToManyField(blank=True, related_name='Machines', to='machine.Machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='MultipleMachine_Front_Machine_ID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MachinesFront', to='machine.Machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='Owner_Team_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='machine',
            name='Owner_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
