# Generated by Django 2.2.4 on 2019-11-25 13:32

from django.db import migrations, models
import machine.models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20191125_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='input_file',
            field=models.FileField(null=True, upload_to=machine.models.get_upload_path, verbose_name='file'),
        ),
    ]
