# Generated by Django 2.2.4 on 2019-11-28 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_auto_20191125_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='AnalysisSource_ColumnsNameInput',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='machine',
            name='AnalysisSource_ColumnsNameOutput',
            field=django_mysql.models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Owner_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ParameterCNN_Shape',
            field=models.CharField(blank=True, default='[null, null, "softmax", null, null, "softmax", null, null, "softmax", null, null, "softmax", null, null, "softmax", null, null, "softmax", null, null, "softmax", null, null, "softmax", null, null, "softmax", null, null, "softmax"]', max_length=400, null=True, verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Project_ColumnsDescription',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='machinemessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
