# Generated by Django 2.2.4 on 2019-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20191128_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='ParameterCNN_Shape',
            field=models.CharField(blank=True, default='[[null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"], [null, null, "softmax"]]', max_length=400, null=True, verbose_name='Shape'),
        ),
    ]
