# Generated by Django 2.2.4 on 2019-12-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='User_APIKey_cb4f22_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='APIKey',
        ),
    ]
