# Generated by Django 2.2.4 on 2019-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLogger',
            fields=[
                ('Log_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTimeCreation', models.DateTimeField(auto_now_add=True)),
                ('TraceBack', models.TextField(blank=True, help_text='JSON traceback()')),
                ('MainModule', models.CharField(help_text='from traceback extract the name of mainmodule', max_length=100)),
                ('MainFunction', models.CharField(help_text='from traceback extract the name of mainfunction', max_length=100)),
                ('Message', models.TextField(blank=True, help_text='text parameter')),
                ('HostName', models.CharField(help_text='hostname of server', max_length=45)),
                ('IP', models.CharField(help_text='ip of server', max_length=100)),
            ],
            options={
                'db_table': 'GlobalLogger',
            },
        ),
        migrations.AddIndex(
            model_name='globallogger',
            index=models.Index(fields=['Log_ID'], name='GlobalLogge_Log_ID_81bae6_idx'),
        ),
        migrations.AddIndex(
            model_name='globallogger',
            index=models.Index(fields=['MainModule'], name='GlobalLogge_MainMod_42762c_idx'),
        ),
        migrations.AddIndex(
            model_name='globallogger',
            index=models.Index(fields=['MainFunction'], name='GlobalLogge_MainFun_5c8e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='globallogger',
            index=models.Index(fields=['HostName'], name='GlobalLogge_HostNam_a01b88_idx'),
        ),
        migrations.AddIndex(
            model_name='globallogger',
            index=models.Index(fields=['IP'], name='GlobalLogge_IP_48d3a0_idx'),
        ),
    ]
